In [1]:
import pandas as pd

In [2]:
# EXTRACTING FROM EXCEL
excel_df=pd.read_csv(r"c:\Users\sindh\OneDrive\Documents\Data science GUVI\Project 1 - Uber eats\Uber_Eats_data.csv")

In [3]:
excel_df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [4]:
excel_df.dtypes

name                             str
online_order                     str
book_table                       str
rate                             str
votes                          int64
phone                            str
location                         str
rest_type                        str
dish_liked                       str
cuisines                         str
approx_cost(for two people)      str
listed_in(type)                  str
listed_in(city)                  str
dtype: object

In [5]:
excel_df['rate'].head(30)

0     4.1/5
1     4.1/5
2     3.8/5
3     3.7/5
4     3.8/5
5     3.8/5
6     4.6/5
7     4.0/5
8     4.2/5
9     4.1/5
10    4.2/5
11    4.2/5
12    4.0/5
13    3.8/5
14    3.8/5
15    3.9/5
16    3.8/5
17    3.9/5
18    3.0/5
19    3.7/5
20    3.6/5
21    3.8/5
22    4.0/5
23    2.8/5
24    3.9/5
25    4.2/5
26    3.9/5
27    4.2/5
28    4.4/5
29    3.8/5
Name: rate, dtype: str

In [6]:
excel_df['rate'].tail(30)

23163    2.5 /5
23164    4.3 /5
23165    4.5 /5
23166    4.1 /5
23167    4.3 /5
23168    4.7 /5
23169    4.6 /5
23170    4.4 /5
23171    4.0 /5
23172    4.1 /5
23173    4.2 /5
23174    4.2 /5
23175    3.9 /5
23176    4.1 /5
23177    4.1 /5
23178    4.2 /5
23179    4.3 /5
23180    4.4 /5
23181    3.9 /5
23182    4.1 /5
23183    4.1 /5
23184    4.1 /5
23185    4.0 /5
23186    3.9 /5
23187    4.0 /5
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, dtype: str

In [7]:
excel_df['rate'].unique

<bound method Series.unique of 0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23193, dtype: str>

In [8]:
excel_df['rate'] = excel_df['rate'].str.split('/').str[0]

In [9]:
excel_df['rate'] = excel_df['rate'].str.strip()

In [10]:
excel_df['rate'].value_counts()

rate
3.9    3238
4.0    2860
4.1    2786
3.8    2473
4.2    2097
4.3    1671
3.7    1639
4.4    1123
3.6     875
4.5     630
3.5     482
3.4     351
2.8     315
2.9     309
3.1     307
4.6     294
3.0     291
3.2     249
3.3     218
2.7     190
4.7     167
NEW     147
2.6     138
4.8      66
2.5      57
4.9      55
2.4      54
2.3      45
2.2      26
2.1      24
2.0      11
1.8       5
Name: count, dtype: int64

In [11]:
excel_df['rate']=pd.to_numeric(excel_df['rate'],errors='coerce')

In [12]:
excel_df['rate'].dtype

dtype('float64')

In [13]:
excel_df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [14]:
excel_df.dtypes

name                               str
online_order                       str
book_table                         str
rate                           float64
votes                            int64
phone                              str
location                           str
rest_type                          str
dish_liked                         str
cuisines                           str
approx_cost(for two people)        str
listed_in(type)                    str
listed_in(city)                    str
dtype: object

In [15]:
excel_df['approx_cost(for two people)']

0          800
1          800
2          800
3          300
4          600
         ...
23188    1,200
23189    2,000
23190    1,200
23191      800
23192    2,500
Name: approx_cost(for two people), Length: 23193, dtype: str

In [16]:
excel_df.isnull().sum()

name                             0
online_order                     0
book_table                       0
rate                           147
votes                            0
phone                            0
location                         0
rest_type                        0
dish_liked                       0
cuisines                         0
approx_cost(for two people)      0
listed_in(type)                  0
listed_in(city)                  0
dtype: int64

In [17]:
excel_df['approx_cost(for two people)'] = (
    excel_df['approx_cost(for two people)']
    .str.replace(',', '', regex=False)
)

In [18]:
excel_df['approx_cost(for two people)']=pd.to_numeric(excel_df['approx_cost(for two people)'],errors='coerce')

In [19]:
excel_df.dtypes

name                               str
online_order                       str
book_table                         str
rate                           float64
votes                            int64
phone                              str
location                           str
rest_type                          str
dish_liked                         str
cuisines                           str
approx_cost(for two people)      int64
listed_in(type)                    str
listed_in(city)                    str
dtype: object

In [20]:
excel_df['name'].tail(20)

23173                                       Biere Societee
23174                              Uno Chicago Bar & Grill
23175                                    Amoeba Sports Bar
23176                                     One For The Road
23177                                    Whitefield Social
23178               The Whitefield Arms Pub & Microbrewery
23179                                      The Irish House
23180                             Shizusan Shophouse & Bar
23181           Kava Kitchen & Bar - Fairfield by Marriott
23182                                   Harry's Bar + Cafe
23183                                              BAR BAR
23184                                        The Beer Cafe
23185                                    Pablo's Gastrobar
23186                                 Oliver's Pub & Diner
23187                                              Smaaash
23188                                   Izakaya Gastro Pub
23189          M Bar - Bengaluru Marriott Hotel Whitefield
23190                               Keys Cafe - Keys Hotel
23191                                              Bhagini
23192    Chime - Sheraton Grand Bengaluru Whitefield Ho...
Name: name, dtype: str

In [21]:

excel_df['book_table'].value_counts(dropna=False)

book_table
No     17071
Yes     6122
Name: count, dtype: int64

In [22]:
excel_df['online_order'].value_counts(dropna=False)

online_order
Yes    16358
No      6835
Name: count, dtype: int64

In [23]:
excel_df['rest_type'].isna().sum()

np.int64(0)

In [24]:
excel_df['rest_type'].value_counts(dropna=False)

rest_type
Casual Dining                7349
Quick Bites                  5240
Cafe                         2325
Dessert Parlor               1076
Casual Dining, Bar            984
                             ...
Bar, Pub                        5
Club, Casual Dining             4
Dessert Parlor, Kiosk           2
Dhaba                           1
Food Court, Casual Dining       1
Name: count, Length: 73, dtype: int64

In [25]:
excel_df['location'].tail(20)

23173                    Whitefield
23174                    Whitefield
23175                    Whitefield
23176                    Whitefield
23177                    Whitefield
23178                    Whitefield
23179                    Whitefield
23180                    Whitefield
23181                    Whitefield
23182                    Whitefield
23183                    Whitefield
23184                    Whitefield
23185                    Whitefield
23186                    Whitefield
23187                    Whitefield
23188                    Whitefield
23189                    Whitefield
23190                    Whitefield
23191                    Whitefield
23192    ITPL Main Road, Whitefield
Name: location, dtype: str

In [26]:
excel_df[excel_df['name'].str.contains('Ã', na=False)]['name']

9        CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
89       CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
258      CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
440        Bohra Bohra CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©
2075             CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Felix
                               ...
21693    KazÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
21737    CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
21783    CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
22011    KazÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
22721    Foreign CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ...
Name: name, Length: 149, dtype: str

In [27]:
excel_df[excel_df['name'] == '1947'].value_counts()

name  online_order  book_table  rate  votes  phone                                 location      rest_type      dish_liked                                                                                        cuisines                            approx_cost(for two people)  listed_in(type)  listed_in(city)
1947  No            Yes         4.0   808    080 26791213\r\n+91 9739989446        Banashankari  Casual Dining  Salads, Panneer Butter Masala, Rabri, Gajar Ka Halwa, Manchow Soup, Aam Panna, Tomato Basil Soup  North Indian, Chinese               850                          Delivery         Banashankari       1
                                             080 26791213\r\r\r\r\n+91 9739989446  Banashankari  Casual Dining  Salads, Panneer Butter Masala, Rabri, Gajar Ka Halwa, Manchow Soup, Aam Panna, Tomato Basil Soup  North Indian, Chinese               850                          Dine-out         Banashankari       1
                                4.1   2303   080 41261947\r\n+91 9739989453        Jayanagar     Casual Dining  Palak Paneer, Aam Panna, Crispy Corn, Gajar Ka Halwa, Panipuri, Kulfi, Salads                     North Indian, Chinese               950                          Buffet           Basavanagudi       1
                                                                                                                                                                                                                                                                                   Delivery         Basavanagudi       1
                                      2359   080 41261947\n+91 9739989453          Jayanagar     Casual Dining  Pasta, Tomato Soup, Salad, Kulcha, Chaat, Kulfi, Panipuri                                         North Indian, Chinese               950                          Dine-out         Basavanagudi       1
                                      2309   080 41261947\r\n+91 9739989453        Jayanagar     Casual Dining  Palak Paneer, Aam Panna, Crispy Corn, Gajar Ka Halwa, Panipuri, Kulfi, Salads                     North Indian, Chinese               950                          Buffet           Jayanagar          1
                                      2312   080 41261947\r\n+91 9739989453        Jayanagar     Casual Dining  Palak Paneer, Aam Panna, Crispy Corn, Gajar Ka Halwa, Panipuri, Kulfi, Salads                     North Indian, Chinese               950                          Delivery         Jayanagar          1
                                      2317   080 41261947\r\n+91 9739989453        Jayanagar     Casual Dining  Palak Paneer, Aam Panna, Crispy Corn, Gajar Ka Halwa, Panipuri, Kulfi, Salads                     North Indian, Chinese               950                          Dine-out         Jayanagar          1
                                4.0   1070   080 41314321\n+91 9739989448          Malleshwaram  Casual Dining  Jal-jeera, Roti, Dhokla, Biryani, Kheer, Chaach, Dal Tadka                                        North Indian, Chinese               950                          Buffet           Malleshwaram       1
                                                                                                                                                                                                                                                                                   Delivery         Malleshwaram       1
                                                                                                                                                                                                                                                                                   Dine-out         Malleshwaram       1
                                3.9   621    +91 9739989491\n080 41321947          Rajajinagar   Casual Dining  Manchurian, Vegetarian, Sweet Corn Soup, Paneer Tikka, Noodles, Rabri, Veg Fried Rice             North Indian, Chinese, Continental  1000                         Buffet           Rajajinagar        1
                                      620    +91 9739989491\n080 41321947          Rajajinagar   Casual Dining  Manchurian, Vegetarian, Sweet Corn Soup, Paneer Tikka, Noodles, Rabri, Veg Fried Rice             North Indian, Chinese, Continental  1000                         Delivery         Rajajinagar        1
                                                                                                                                                                                                                                                                                   Dine-out         Rajajinagar        1
Name: count, dtype: int64

In [28]:
excel_df['phone'] = (
    excel_df['phone']
    .str.replace('\r', '', regex=False)
    .str.replace('\n', ', ', regex=False)
)

In [29]:
excel_df[excel_df.duplicated(keep=False)]

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
1517,The Fisherman's Wharf,Yes,Yes,4.4,4099,080 49653108,Sarjapur Road,"Casual Dining, Bar","Sea Food, Caesar Salad, Jumbo Prawns, Cocktail...","Seafood, Goan, North Indian, Continental, Asian",1400,Buffet,Bellandur
1532,The Fisherman's Wharf,Yes,Yes,4.4,4099,080 49653108,Sarjapur Road,"Casual Dining, Bar","Sea Food, Caesar Salad, Jumbo Prawns, Cocktail...","Seafood, Goan, North Indian, Continental, Asian",1400,Buffet,Bellandur
1996,OPUS Club,No,Yes,4.4,1496,"+91 8046444777, +91 7349734900",Sarjapur Road,Pub,"Biryani, Cocktails, Nachos, Mocktails, Long Is...","Continental, Italian, North Indian, Mexican",1900,Drinks & nightlife,Bellandur
1997,Float,Yes,Yes,4.4,3061,"+91 9066887042, +91 9066887086",Marathahalli,"Casual Dining, Bar","Butter Fish, Chicken Burritos, Cocktails, Mock...","North Indian, Japanese",1500,Drinks & nightlife,Bellandur
1998,OPUS Club,No,Yes,4.4,1496,"+91 8046444777, +91 7349734900",Sarjapur Road,Pub,"Biryani, Cocktails, Nachos, Mocktails, Long Is...","Continental, Italian, North Indian, Mexican",1900,Drinks & nightlife,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20784,BTDT? Been There Done That,No,Yes,4.3,962,080 49652655,Indiranagar,"Bar, Casual Dining","Cocktails, Momos, Pizza, Mushroom Ragout, Roti...","European, Continental, Asian, Finger Food",1300,Drinks & nightlife,Old Airport Road
20785,Tipsy Bull - The Bar Exchange,No,Yes,4.6,3173,080 49652910,Indiranagar,"Bar, Casual Dining","Cocktails, Peri Peri Chicken, Biryani, Mocktai...","Chinese, Continental, North Indian, Mexican",1400,Drinks & nightlife,Old Airport Road
20786,BTDT? Been There Done That,No,Yes,4.3,962,080 49652655,Indiranagar,"Bar, Casual Dining","Cocktails, Momos, Pizza, Mushroom Ragout, Roti...","European, Continental, Asian, Finger Food",1300,Drinks & nightlife,Old Airport Road
22001,ShakesBierre,No,Yes,4.4,409,080 49653253,Brigade Road,"Microbrewery, Casual Dining","Cocktails, Mocktails, Pizza, Sweet Yogurt, Juj...","Asian, Continental, European, North Indian",1500,Drinks & nightlife,Residency Road
22014,ShakesBierre,No,Yes,4.4,409,080 49653253,Brigade Road,"Microbrewery, Casual Dining","Cocktails, Mocktails, Pizza, Sweet Yogurt, Juj...","Asian, Continental, European, North Indian",1500,Drinks & nightlife,Residency Road

In [30]:
excel_df = excel_df.drop_duplicates()

In [31]:
excel_df.head(20)

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,"080 42297555, +91 9743772233",Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,"+91 8026612447, +91 9901210005",Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
5,Timepass Dinner,Yes,No,3.8,286,"+91 9980040002, +91 9980063005",Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,Buffet,Banashankari
6,Onesta,Yes,Yes,4.6,2556,"080 48653961, 080 48655715",Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,Cafes,Banashankari
7,Penthouse Cafe,Yes,No,4.0,324,"+91 8884135549, +91 9449449316",Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,Cafes,Banashankari
8,Smacznego,Yes,No,4.2,504,"+91 9945230807, +91 9743804471",Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,Cafes,Banashankari
9,CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...,Yes,No,4.1,402,"080 26724489, +91 7406048982",Banashankari,Cafe,"Waffles, Pasta, Crispy Chicken, Honey Chilli C...",Cafe,500,Cafes,Banashankari
10,Cafe Shuffle,Yes,Yes,4.2,150,+91 9742166777,Banashankari,Cafe,"Mocktails, Peri Fries, Lasagne, Pizza, Chicken...","Cafe, Italian, Continental",600,Cafes,Banashankari
11,The Coffee Shack,Yes,Yes,4.2,164,+91 9731644212,Banashankari,Cafe,"Coffee, Spaghetti, Pancakes, Nachos, Pasta, Sa...","Cafe, Chinese, Continental, Italian",500,Cafes,Banashankari
12,Caf-Eleven,No,No,4.0,424,080 49577715,Banashankari,Cafe,"Sandwich, Omelette, Ice Tea, Virgin Mojito, Ho...","Cafe, Continental",450,Cafes,Banashankari
13,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Cafes,Banashankari
14,Cafe Vivacity,Yes,No,3.8,90,"080 26768182, +91 9845704455",Banashankari,Cafe,"Garlic Bread, Burgers, Sandwiches, Pizza, Hot ...",Cafe,650,Cafes,Banashankari
15,Catch-up-ino,Yes,No,3.9,133,"+91 9972988038, +91 9900121238",Banashankari,Cafe,"Momos, Mushroom Bruschettas, Jalapeno Cheeseba...","Cafe, Fast Food, Continental, Chinese, Momos",800,Cafes,Banashankari
16,Kirthi's Biryani,Yes,No,3.8,144,"080 26711554, +91 9741406338",Banashankari,Cafe,"Pasta, Gelato, Garlic Bread, Mojito, Nachos, P...","Chinese, Cafe, Italian",700,Cafes,Banashankari
17,T3H Cafe,No,No,3.9,93,+91 8884726600,Banashankari,Cafe,"Cheese Maggi, Peri Peri Fries, Pasta Arrabiata","Cafe, Italian, American",300,Cafes,Banashankari
18,The Vintage Cafe,Yes,No,3.0,62,"+91 9880016665, +91 8217311687",Banashankari,Cafe,"Burgers, Caramel Milkshake, Iced Coffee, Iced Tea","Cafe, French, North Indian",400,Cafes,Banashankari
19,Woodee Pizza,Yes,No,3.7,180,+91 7406822844,Banashankari,Cafe,"Pizza, Garlic Bread","Cafe, Pizza, Fast Food, Beverages",500,Cafes,Banashankari

In [32]:
for col in excel_df.select_dtypes(include='object'):
    excel_df[col] = excel_df[col].str.strip()

C:\Users\sindh\AppData\Local\Temp\ipykernel_11524\1424202304.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in excel_df.select_dtypes(include='object'):

In [33]:
repr(excel_df.loc[0, 'name'])

"'Jalsa'"

In [34]:
excel_df['name'] = excel_df['name'].str.strip("'")

In [35]:
excel_df['name'].str.startswith("'").sum()

np.int64(0)

In [36]:
excel_df[['rate','votes','approx_cost(for two people)']].describe()

               rate         votes  approx_cost(for two people)
count  23005.000000  23151.000000                 23151.000000
mean       3.903899    599.995637                   755.211006
std        0.426407   1114.103076                   521.089295
min        1.800000      0.000000                    40.000000
25%        3.800000    101.000000                   400.000000
50%        4.000000    221.000000                   600.000000
75%        4.200000    584.000000                  1000.000000
max        4.900000  16832.000000                  6000.000000

In [37]:
import sqlite3

conn = sqlite3.connect("uber_eats.db")

In [38]:
excel_df.to_sql(
    name="restaurants",
    con=conn,
    if_exists="replace",
    index=False
)

23151

In [39]:
query = "SELECT name FROM sqlite_master WHERE type='table';"

pd.read_sql(query, conn)

            name
0       Order_id
1  Order_details
2    restaurants

In [40]:
query = """
SELECT *
FROM restaurants
LIMIT 5
"""

pd.read_sql(query, conn)

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,"080 42297555, +91 9743772233",Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,"+91 8026612447, +91 9901210005",Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [41]:
excel_df["approx_cost(for two people)"].describe()

count    23151.000000
mean       755.211006
std        521.089295
min         40.000000
25%        400.000000
50%        600.000000
75%       1000.000000
max       6000.000000
Name: approx_cost(for two people), dtype: float64

In [42]:
excel_df[['approx_cost(for two people)', 'rate']].corr()

                             approx_cost(for two people)      rate
approx_cost(for two people)                     1.000000  0.314478
rate                                            0.314478  1.000000

In [43]:
#What is the relationship between restaurant cost and rating?
 #Business Value: Determines whether higher pricing translates to better customer perception.


corr = excel_df['approx_cost(for two people)'].corr(excel_df['rate'])

q10 = pd.DataFrame({
    'Metric':['Cost vs Rating Correlation'],
    'Correlation':[round(corr,3)]
})

In [44]:
fig = px.scatter(
    excel_df,
    x='approx_cost(for two people)',
    y='rate',
    title='Restaurant Cost vs Rating'
)

st.plotly_chart(fig, use_container_width=True)

NameError: name 'px' is not defined